[build]
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
  Content-Type = "application/manifest+json; charset=utf-8"
